# Generated by Django 3.2.6 on 2021-08-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(default='default.png', upload_to='farmer/')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=50)),
                ('Address', models.TextField(default='', max_length=50)),
                ('Country', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Farmer',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Master',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.CharField(max_length=10)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(default='default.png', upload_to='seller/')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=50)),
                ('Address', models.TextField(default='', max_length=50)),
                ('Country', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('IsActive', models.BooleanField(default=False)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.master')),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(default='default.png', upload_to='seller/products/')),
                ('Categories', models.CharField(choices=[('Vegitable_seeds', 'Vegitable_seeds'), ('Flower_seeds', 'Flower_seeds'), ('Fruits_seeds', 'Fruits_seeds'), ('Hybrid_seeds', 'Hybrid_seeds'), ('Herbs_seeds', 'Herbs_seeds'), ('Forestry_Tree seeds', 'Forestry_tree seeds'), ('Chemical_fertilizers', 'Chemical_fertilizers'), ('Gardening_Tools', 'Gardening_tools')], max_length=50)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Unit', models.CharField(choices=[('50Kg', '50kg'), ('1Kg', '1kg'), ('500g', '500g'), ('200g', '200g'), ('100g', '100g'), ('50g', '50g'), ('25g', '25g'), ('10g', '10g'), ('5g', '5g'), ('1Ltr', '1ltr'), ('500ML', '500ml'), ('200M', '200m'), ('100ML', '100ml'), ('Piece', 'Piece')], max_length=5)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.seller')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.farmer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.product')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.role'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Review', models.CharField(max_length=2000)),
                ('Farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.farmer')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.master')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.AddField(
            model_name='farmer',
            name='Master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.master'),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipping_Name', models.CharField(default='', max_length=20)),
                ('Phone_Number', models.IntegerField()),
                ('House_Number', models.IntegerField()),
                ('Floor_Number', models.IntegerField()),
                ('Country', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=15)),
                ('City', models.CharField(default='', max_length=15)),
                ('Area', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=40)),
                ('Pincode', models.IntegerField()),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.master')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.farmer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawsApp.product')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
