# Generated by Django 3.2.6 on 2021-08-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='Image',
            field=models.FileField(default='default.png', upload_to='farmer/profile_img/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Image',
            field=models.FileField(default='default.png', upload_to='seller/profile_img/'),
        ),
    ]
